{
    'name': 'Hospital Management',
    'version': '15.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'Invoices & Payments',
    'sequence': '10',
    'license': 'AGPL-3',
    'description': "",
    'website': 'https://www.odoo.com/app/invoicing',
    'depends': ['base', 'mail',  'portal'],
    'demo': [],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'patient.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
